// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFFZFPwA8QmM9oOyS62orMUOxbkSIadBU',
    appId: '1:905506199750:android:2f60a5035e7d4477171fc7',
    messagingSenderId: '905506199750',
    projectId: 'korsord-crosswords',
    storageBucket: 'korsord-crosswords.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-AN9c6O_b0P8WMvgFis4QHWZ2es7Knns',
    appId: '1:905506199750:ios:076956ea14f47190171fc7',
    messagingSenderId: '905506199750',
    projectId: 'korsord-crosswords',
    storageBucket: 'korsord-crosswords.firebasestorage.app',
    androidClientId: '905506199750-lo2vsek10a165uvgm6ut9slav3rmhv8d.apps.googleusercontent.com',
    iosClientId: '905506199750-uh0545oo0r06tm58u2ohf7oq7nurml4m.apps.googleusercontent.com',
    iosBundleId: 'com.xevenition.crosswords',
  );

}